@startuml
!pragma layout smetana

title UC7: MedicationLog

actor "Patient" as u
participant "MedicationLogView" as v
participant "MedicationLogController" as c
participant "MedicationLog" as m
database "SQLite" as db

u -> v : Opens medication screen
v -> c : show(stage)
c -> db : SELECT * FROM medication_log WHERE journey_id = ?
db --> c : ResultSet
c --> v : showMedicationList()
v --> u : Shows previous medication entries

u -> v : Clicks Add Medication
c --> v : showCreateMedicationScreen()
v --> u : Shows screen with fields

u -> v : Fills in name, dose and date
u -> v : Clicks Save
v -> c : handleSave()

alt Fields are empty
  c --> v : showError()
  v --> u : "One or more required fields are empty"
else All OK
  c -> m : new MedicationLog(date, medication, dose, taken)
  c -> db : INSERT INTO medication_log VALUES (?, ?, ?, ?, ?)
  db --> c : OK
  c --> v : showUpdatedList()
  v --> u : List updated
end

u -> v : Marks medication as taken
v -> c : handleMarkTaken()
c -> db : UPDATE medication_log SET taken = 1 WHERE id = ?
db --> c : OK
c --> v : showUpdatedList()
v --> u : Medication marked as taken

@enduml